const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const url = process.env.RGATU_TEST_URL || 'http://127.0.0.1:4173';
  const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
  const context = await browser.newContext({viewport:{width:375,height:812},deviceScaleFactor:1,timezoneId:'Europe/Moscow',locale:'ru-RU'});
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(url);
  await page.waitForFunction(()=>document.querySelector('#group-search'));
  // Let initial offline installation finish so the first controller change cannot interrupt a selection.
  await page.evaluate(async()=>{if('serviceWorker' in navigator)await navigator.serviceWorker.ready;});
  await page.waitForLoadState('networkidle');
  const screenshots = path.resolve('build/screenshots');
  fs.mkdirSync(screenshots,{recursive:true});
  await page.screenshot({path:path.join(screenshots,'01-group.png'),fullPage:true});
  await page.fill('#group-search','ЗВС-26');
  assert.equal(await page.locator('.group-row').count(),1);
  await page.locator('.group-row').click();
  await page.click('#continue-group');
  await page.waitForSelector('.group-switch');
  assert.equal(await page.evaluate(()=>localStorage.getItem('rgatu.group')),'ЗВС-26');
  await page.locator('#day-picker').fill('2026-10-05');
  await page.locator('#day-picker').dispatchEvent('change');
  await page.waitForSelector('.lesson');
  assert.match(await page.locator('.lesson').first().innerText(),/Экономика/);
  assert.match(await page.locator('.lesson').first().innerText(),/Фоменко С\.А\./);
  assert.match(await page.locator('.lesson').first().innerText(),/1-212/);
  await page.screenshot({path:path.join(screenshots,'02-day.png'),fullPage:true});
  await page.reload();
  await page.waitForSelector('.group-switch');
  assert.match(await page.locator('.group-switch').innerText(),/ЗВС-26/);
  assert.equal(await page.locator('#group-search').count(),0);
  await page.click('a[href="#session"]');
  await page.fill('#subject-search','Фоменко');
  assert.ok(await page.locator('.lesson').count()>0);
  for(const teacher of await page.locator('.teacher').allTextContents())assert.match(teacher,/Фоменко/);
  await page.fill('#subject-search','ничегоненайти');
  assert.match(await page.locator('.empty').innerText(),/Ничего не нашлось/);
  await page.click('[data-action=reset-subject]');
  await page.click('[data-action=kind][data-value="ЛР"]');
  for(const kind of await page.locator('.kind').allTextContents())assert.equal(kind,'Лабораторная');
  await page.click('a[href="#profile"]');
  await page.selectOption('#theme','dark');
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.screenshot({path:path.join(screenshots,'03-profile-dark.png'),fullPage:true});
  // Content stays inside narrow and landscape viewports, including enlarged text.
  for(const viewport of [{width:320,height:740},{width:812,height:375},{width:768,height:1024}]) {
    await page.setViewportSize(viewport);
    await page.click('a[href="#day"]');
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  }
  await page.setViewportSize({width:375,height:812});
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.addStyleTag({content:'html{font-size:24px!important}'});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await page.reload();
  await page.waitForSelector('.group-switch');
  // The installed shell and complete embedded timetable remain usable offline.
  await context.setOffline(true);
  await page.reload();
  await page.waitForSelector('.group-switch');
  await page.click('a[href="#session"]');
  assert.ok(await page.locator('.lesson').count()>0);
  await page.click('a[href="#profile"]');
  await page.click('[data-action=refresh]');
  assert.match(await page.locator('#notice').innerText(),/нет интернета/);
  await context.setOffline(false);
  await page.click('[data-action=group]');
  await page.fill('#group-search','ЗИС-22-2');
  await page.locator('.group-row').click();
  await page.click('#continue-group');
  assert.equal(await page.evaluate(()=>localStorage.getItem('rgatu.group')),'ЗИС-22-2');
  assert.match(await page.locator('.source-banner').innerText(),/сессия закончилась/);
  await page.click('a[href="#profile"]');
  await page.selectOption('#theme','light');
  const bodyText = await page.locator('body').innerText();
  assert.doesNotMatch(bodyText,/PWA|API|Cloudflare|кэш|база данных|JavaScript/i);
  assert.deepEqual(errors,[]);
  const manifest = await (await context.request.get(url+'/manifest.webmanifest')).json();
  assert.equal(manifest.display,'standalone');
  for(const icon of manifest.icons)assert.equal((await context.request.get(url+icon.src)).status(),200);
  console.log('PASS: group selection and persistence, exact schedule fields, search/filter, subgroup change, past-session state, themes, phone/landscape/tablet, enlarged text, reduced motion, offline reload, manifest and icons, no technical UI labels.');
  await browser.close();
})().catch(error=>{console.error(error);process.exit(1);});
